
version: '2.1'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ~/volumes/mariadb/conf:/etc/mysql
      - ~/volumes/mariadb/data:/var/lib/mysql