// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

#include "action.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace gameplay {
class EventPacketDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EventPacket>
      _instance;
} _EventPacket_default_instance_;
}  // namespace gameplay
namespace protobuf_action_2eproto {
static void InitDefaultsEventPacket() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gameplay::_EventPacket_default_instance_;
    new (ptr) ::gameplay::EventPacket();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gameplay::EventPacket::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_EventPacket =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEventPacket}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_EventPacket.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gameplay::EventPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gameplay::EventPacket, session_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gameplay::EventPacket, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gameplay::EventPacket, radius_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gameplay::EventPacket, send_time_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gameplay::EventPacket)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::gameplay::_EventPacket_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "action.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014action.proto\022\010gameplay\"\230\001\n\013EventPacket"
      "\022\022\n\nsession_id\030\001 \001(\005\022.\n\004type\030\002 \001(\0162 .gam"
      "eplay.EventPacket.ActionType\022\016\n\006radius\030\003"
      " \001(\002\022\021\n\tsend_time\030\004 \001(\002\"\"\n\nActionType\022\010\n"
      "\004MOVE\020\000\022\n\n\006ATTACK\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "action.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_action_2eproto
namespace gameplay {
const ::google::protobuf::EnumDescriptor* EventPacket_ActionType_descriptor() {
  protobuf_action_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_action_2eproto::file_level_enum_descriptors[0];
}
bool EventPacket_ActionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const EventPacket_ActionType EventPacket::MOVE;
const EventPacket_ActionType EventPacket::ATTACK;
const EventPacket_ActionType EventPacket::ActionType_MIN;
const EventPacket_ActionType EventPacket::ActionType_MAX;
const int EventPacket::ActionType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void EventPacket::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EventPacket::kSessionIdFieldNumber;
const int EventPacket::kTypeFieldNumber;
const int EventPacket::kRadiusFieldNumber;
const int EventPacket::kSendTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EventPacket::EventPacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_action_2eproto::scc_info_EventPacket.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:gameplay.EventPacket)
}
EventPacket::EventPacket(const EventPacket& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&session_id_, &from.session_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&send_time_) -
    reinterpret_cast<char*>(&session_id_)) + sizeof(send_time_));
  // @@protoc_insertion_point(copy_constructor:gameplay.EventPacket)
}

void EventPacket::SharedCtor() {
  ::memset(&session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&send_time_) -
      reinterpret_cast<char*>(&session_id_)) + sizeof(send_time_));
}

EventPacket::~EventPacket() {
  // @@protoc_insertion_point(destructor:gameplay.EventPacket)
  SharedDtor();
}

void EventPacket::SharedDtor() {
}

void EventPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EventPacket::descriptor() {
  ::protobuf_action_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_action_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EventPacket& EventPacket::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_action_2eproto::scc_info_EventPacket.base);
  return *internal_default_instance();
}


void EventPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:gameplay.EventPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&send_time_) -
      reinterpret_cast<char*>(&session_id_)) + sizeof(send_time_));
  _internal_metadata_.Clear();
}

bool EventPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gameplay.EventPacket)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 session_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &session_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .gameplay.EventPacket.ActionType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::gameplay::EventPacket_ActionType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float radius = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &radius_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float send_time = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &send_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gameplay.EventPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gameplay.EventPacket)
  return false;
#undef DO_
}

void EventPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gameplay.EventPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 session_id = 1;
  if (this->session_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->session_id(), output);
  }

  // .gameplay.EventPacket.ActionType type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // float radius = 3;
  if (this->radius() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->radius(), output);
  }

  // float send_time = 4;
  if (this->send_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->send_time(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gameplay.EventPacket)
}

::google::protobuf::uint8* EventPacket::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gameplay.EventPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 session_id = 1;
  if (this->session_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->session_id(), target);
  }

  // .gameplay.EventPacket.ActionType type = 2;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // float radius = 3;
  if (this->radius() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->radius(), target);
  }

  // float send_time = 4;
  if (this->send_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->send_time(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gameplay.EventPacket)
  return target;
}

size_t EventPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gameplay.EventPacket)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 session_id = 1;
  if (this->session_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->session_id());
  }

  // .gameplay.EventPacket.ActionType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // float radius = 3;
  if (this->radius() != 0) {
    total_size += 1 + 4;
  }

  // float send_time = 4;
  if (this->send_time() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EventPacket::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gameplay.EventPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const EventPacket* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EventPacket>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gameplay.EventPacket)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gameplay.EventPacket)
    MergeFrom(*source);
  }
}

void EventPacket::MergeFrom(const EventPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gameplay.EventPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.session_id() != 0) {
    set_session_id(from.session_id());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.radius() != 0) {
    set_radius(from.radius());
  }
  if (from.send_time() != 0) {
    set_send_time(from.send_time());
  }
}

void EventPacket::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gameplay.EventPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EventPacket::CopyFrom(const EventPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gameplay.EventPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EventPacket::IsInitialized() const {
  return true;
}

void EventPacket::Swap(EventPacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EventPacket::InternalSwap(EventPacket* other) {
  using std::swap;
  swap(session_id_, other->session_id_);
  swap(type_, other->type_);
  swap(radius_, other->radius_);
  swap(send_time_, other->send_time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EventPacket::GetMetadata() const {
  protobuf_action_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_action_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace gameplay
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::gameplay::EventPacket* Arena::CreateMaybeMessage< ::gameplay::EventPacket >(Arena* arena) {
  return Arena::CreateInternal< ::gameplay::EventPacket >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
